### ISSUE TITLE
Search does not match on partial words or phrases

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-search#168]
should search in v2 return partial matches? I have a project called “neurodesk” and if I search for “neuro” I get nothing; but searching for “neurodesk” I get the right result

Reported by Rok

on Renku version 0.54.2 - not sure exactly which search version this corresponds to but we can easily check

We should probably set solr up to match in the case that Rok describes above

**Comment by eikek** [comment]
Probably the default setup doesn't recognize this as a compound word and so doesn't  split it. We can maybe setup something, like [based on a dictionary](https://solr.apache.org/guide/solr/latest/indexing-guide/language-analysis.html#dictionary-compound-word-token-filter) or a custom filter.

**Comment by eikek** [comment]
Closed with #179
