### ISSUE TITLE
Add keywords project property

### ISSUE THREAD

**Issue by eikek** [SwissDataScienceCenter/renku-search#88]
Renku schema now defines a `keywords` property for projects. This needs to be integrated into search:

- Add property to project document (using proper type and solr schema)
- Adopt code, e.g. `SerializeDeserializeSpec`, `EventsGenerators`, `ProjectEventsGenerator`, `DocumentMerger`, etc
- extend user query to support `keyword:<kw1>[,kw2,...]` syntax
- add keywords to `content_all` field so they are searched when using "free" query

**Comment by jachro** [comment]
done as #92
